data_ingestion:
  data_path: 'data/src'
  data_path_dest: 'data/raw'
  ticker: 'DAX40' # 'SP500' 'NQ100'
  data_source: 'questdb'
  table_name: 'DUKASCOPY_{ticker}_OHLC_{timeframe}'
  start_date: '2021-07-01'
  end_date: '2026-08-14'
  timeframes: ['10s', '1m', '2m', '3m', '4m', '5m', '10m', '15m', '20m', '30m', '1h', '2h', '4h', '1d']
  index_barrier: 1
  index_base: 5
  indexes_higher: [6,7,8,9,10]
  file_name: '{ticker}-{timeframe}-futures.parquet'
  high_time_col: 'High'
  low_time_col: 'Low'
  high_time_col_wavelet: 'Close_wavelet'
  low_time_col_wavelet: 'Close_wavelet'

data_preprocessing:
  data_path: 'data/raw'
  data_path_dest: 'data/interim'
  ticker: 'DAX40' # 'SP500' 'NQ100'
  index_base: 5
  indexes_higher: [6,7,8,9,10]
  timeframes: ['10s', '1m', '2m', '3m', '4m', '5m', '10m', '15m', '20m', '30m', '1h', '2h', '4h', '1d']
  timeframe_scalers: [0.22, 0.44, 0.63, 0.77, 0.89, 1, 1.4, 1.7, 2, 2.4, 3.4, 4.8, 6.8, 9.6]
  file_name: 'data_ohlc_{timeframe}.csv'
  local_timezone: "America/New_York" # 'Europe/Berlin'

model_building:
  data_path: 'data/interim'
  models_path: 'data/models'
  ticker: 'DAX40' # 'SP500' 'NQ100'
  index_base: 5
  indexes_higher: [7,10]
  timeframes: ['10s', '1m', '2m', '3m', '4m', '5m', '10m', '15m', '20m', '30m', '1h', '2h', '4h', '1d']
  timeframe_scalers: [0.22, 0.44, 0.63, 0.77, 0.89, 1, 1.4, 1.7, 2, 2.4, 3.4, 4.8, 6.8, 9.6]
  timeframe_minutes: [0, 1, 2, 3, 4, 5, 10, 15, 20, 30, 60, 120, 240, 1440]
  file_name: 'data_static_features_{timeframe}.csv'
  list_X: [
    'ha_open',
    'ha_high',
    'ha_low',
    'ha_close',
    # 'Open',
    # 'High',
    # 'Low',
    # 'Close',
    #'midprice',
    #'macdsignal',

    #'sar',
    # 'tenkan_sen',
    #'ema1',
    #'sma1',
    # 'kijun_sen',
    #'lowerband',
    'sine',
    #'middleband',
    #'upperband',
    'sine_diff_slope_2',
    #'ema2',
    #'sma2',
    'sine_diff_slope_5',
    'kama_trend_slow',
    'kama_trend_fast',
    'kama_trend_slow_diff',
    'kama_trend_fast_diff',
    'kama_trend_slow_diff2',
    'kama_trend_fast_diff2',
    'macdhist',
    'sma_cross',
    #'log_ret_1',
    'lowerband_r',
    #'down_displacement_low',
    #'down_displacement_high',
    #'bullish_gap_size',
    #'dc_market_regime',
    #'displacement',
    #'bearish_gap_size',
    #'macd',
    'stochk_slope',
    #'dc_market_regime_ema',
    #'dc_market_regime_wma',
    'dc_market_regime_ema_log',
    'ha_slope_2',
    'ema_cross',
    'log_ret_ha_1',
    'log_ret_ha_2',
    'log_ret_ha_3',
    # 'log_ret_ha_4',
    # 'log_ret_ha_5',
    # 'log_ret_2',
    'ppo',
    'upperband_r',
    'sar_r',
    #'ha_slope_15',
    'stochd',
    'kama_diff',
    #'bullish_gap_low',
    #'bullish_gap_high',
    'bearish_gap',
    #'log_ret_3',
    'rsi_slope',
    'sine_diff',
    'stochrsid',
    #'bearish_gap_low',
    #'bearish_gap_high',
    'stochrsik',
    'bullish_gap',
    #'ha_slope_5',
    'ha_slope_10',
    #'log_ret_4',
    'r_kijun_sen',
    #'ema_ha_upper_wick',
    #'displacement_sma',
    'r_tenkan_sen',
    #'ha_sign',
    #'log_ret_5',
    #'middleband_r',
    #'ema_ha_lower_wick',
    'displacement_hull',
    'displacement_hull_slope',
    'stochk',
    'ema_ha_sign',
    'ema_ha_wickstrength',
    'gap_hull',
    'gap_hull_slope',
    'di_plus',
    'di_minus',
    'cci_ha',
    #'cci',
    'rsi',
    'rsi_ha',
    'di_diff',
    'willr',
    #'vol_short_pca1',
    #'vol_long_pca1',
    #'wavelet_reconstr',
    #'hurst',
    #'hurst_kalman',
    # 'close_wavelet_rolling',
    # 'close_regr_entropy',
    'permutation_entropy',
    # "tail_index_1",
    "skew",
    "petrosian_fd",

    'long_pivot',
    'short_pivot',
    'atr',
    'adx',
    ]
  col_y: ['labeling_multi']
  lags: [1,2]
  version: 2
  model_type: 'svr_regression'
  # model_params_name: 'model_params_{timeframe}_v{version}.json'
  n_trials: 1000
  num_splits: 25
  project_name: 'svr-pipeline'
  evals_strategy: False
  local_timezone: 'Europe/Berlin' # "America/New_York" 'Europe/Berlin'

model_evaluation:
  experiment_id: 109
  run_name: 'Trial_664'
  num_best_trials: 5
  num_evaluations_per_trial: 10

model_analysis:
  experiment_id: 117
  target_metrics: ['optimisation_score', 'total_profit', 'sharpe_ratio', 'win_rate', 'profit_factor', 'total_trades']
  analysis_path: 'data/models/analysis'

model_registration:
  experiment_id: 109
  run_name: 'Trial_664'
  model_tag: 'Staging'


model_trade:
  table_name: 'DUKASCOPY_{ticker}_OHLC_{timeframe}'
  tickstream_table_name: 'TICKSTREAM_{ticker}_OHLC_{timeframe}'
  gaps_table_name: 'GAPS_{ticker}_OHLC_{timeframe}'
  ticker: 'DAX40'
  start_date: '2026-05-01'
  local_timezone: 'Europe/Berlin'
  timeframes: ['10s', '1m', '2m', '3m', '4m', '5m', '10m', '15m', '20m', '30m', '1h', '2h', '4h', '1d']
  timeframe_scalers: [0.22, 0.44, 0.63, 0.77, 0.89, 1, 1.4, 1.7, 2, 2.4, 3.4, 4.8, 6.8, 9.6]
  timeframe_minutes: [0, 1, 2, 3, 4, 5, 10, 15, 20, 30, 60, 120, 240, 1440]
  index_base: 5
  indexes_higher: [7,10]
  file_name: '{ticker}/questdb_static_features_{timeframe}.csv'
  list_X: [
    'ha_open',
    'ha_high',
    'ha_low',
    'ha_close',
    # 'Open',
    # 'High',
    # 'Low',
    # 'Close',
    #'midprice',
    #'macdsignal',

    #'sar',
    # 'tenkan_sen',
    #'ema1',
    #'sma1',
    # 'kijun_sen',
    #'lowerband',
    'sine',
    #'middleband',
    #'upperband',
    'sine_diff_slope_2',
    #'ema2',
    #'sma2',
    'sine_diff_slope_5',
    'kama_trend_slow',
    'kama_trend_fast',
    'kama_trend_slow_diff',
    'kama_trend_fast_diff',
    'kama_trend_slow_diff2',
    'kama_trend_fast_diff2',
    'macdhist',
    'sma_cross',
    #'log_ret_1',
    'lowerband_r',
    #'down_displacement_low',
    #'down_displacement_high',
    #'bullish_gap_size',
    #'dc_market_regime',
    #'displacement',
    #'bearish_gap_size',
    #'macd',
    'stochk_slope',
    #'dc_market_regime_ema',
    #'dc_market_regime_wma',
    'dc_market_regime_ema_log',
    'ha_slope_2',
    'ema_cross',
    'log_ret_ha_1',
    'log_ret_ha_2',
    'log_ret_ha_3',
    # 'log_ret_ha_4',
    # 'log_ret_ha_5',
    # 'log_ret_2',
    'ppo',
    'upperband_r',
    'sar_r',
    #'ha_slope_15',
    'stochd',
    'kama_diff',
    #'bullish_gap_low',
    #'bullish_gap_high',
    'bearish_gap',
    #'log_ret_3',
    'rsi_slope',
    'sine_diff',
    'stochrsid',
    #'bearish_gap_low',
    #'bearish_gap_high',
    'stochrsik',
    'bullish_gap',
    #'ha_slope_5',
    'ha_slope_10',
    #'log_ret_4',
    'r_kijun_sen',
    #'ema_ha_upper_wick',
    #'displacement_sma',
    'r_tenkan_sen',
    #'ha_sign',
    #'log_ret_5',
    #'middleband_r',
    #'ema_ha_lower_wick',
    'displacement_hull',
    'displacement_hull_slope',
    'stochk',
    'ema_ha_sign',
    'ema_ha_wickstrength',
    'gap_hull',
    'gap_hull_slope',
    'di_plus',
    'di_minus',
    'cci_ha',
    #'cci',
    'rsi',
    'rsi_ha',
    'di_diff',
    'willr',
    #'vol_short_pca1',
    #'vol_long_pca1',
    #'wavelet_reconstr',
    #'hurst',
    #'hurst_kalman',
    # 'close_wavelet_rolling',
    # 'close_regr_entropy',
    'permutation_entropy',
    # "tail_index_1",
    "skew",
    "petrosian_fd",

    'long_pivot',
    'short_pivot',
    'atr',
    'adx',
    ]
  lags: [1,2]
