services:
  model_serving:
    hostname: model_serving
    build:
      context: .
      dockerfile: Dockerfile
    image: algo-ml-model-serving:latest
    ports:
      - "${MODEL_SERVE_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI:-http://host.docker.internal:5000/}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    networks:
      - mlflow_net

networks:
    mlflow_net:
        name: mlflow_network
        external: true
